### ISSUE TITLE
[enhancement] Are there any degradation measures in place for trace-etl currently

### ISSUE THREAD

**Issue by jifengzhilong** [XiaoMi/ozhera#324]
Currently, trace-etl requires certain degradation measures to cope with the impact of high traffic volumes.

**Comment by sadadw1** [comment]
I think your suggestion is excellent because the current degradation of trace-etl is not comprehensive enough. Currently, it has the following degradation strategies:

1. In trace-etl-server, filtering can be applied based on spanName and some tags of the span, skipping metric calculations.
2. In trace-etl-es, filtering based on spanName is also possible, skipping tail sampling and subsequent logic, and even not storing the span in the storage system.

Regarding your concerns, I have actually already added some degradation strategies before, including:

1. In trace-etl-server, aggregation of serverIp, sql, and methodName can be performed, making their values ​​become one, with the aim of minimizing the size of the metric data returned by trace-etl-server.
2. Logic for filtering based on application has been added to trace-etl-es.
