### ISSUE TITLE
[bug] Compilation error issue with opentelemetry-java-instrumentation

### ISSUE THREAD

**Issue by sadadw1** [XiaoMi/ozhera#41]
After cloning the project for the first time and trying to compile opentelemetry-java-instrumentation, the following error occurs:

release() argument error.

**Comment by oujinliang** [comment]
hi sadadw1, This is because, during the compilation of opentelemetry-java-instrumentation, it requires information of the current version information, which is extracted from the .git file. Currently, there isn't a .git file in the directory where opentelemetry-java-instrumentation resides, leading to this error. Previously, our suggestion was to run git init in the root directory of opentelemetry-java-instrumentation or to copy the .git folder from the ozhera directory to the root directory of opentelemetry-java-instrumentation.

**Comment by sadadw1** [comment]
Alright, but this situation isn't very user-friendly, and the implementation isn't elegant either. Can we modify it to remove these version-related details? At the very least, we should ensure that new users can compile it without issues.

**Comment by oujinliang** [comment]
Indeed, your suggestion is good. I'll try to remove the release() method to ensure that new users can compile without issues.
