### ISSUE TITLE
Have you considered incorporating the capability of link topology into your project? 

### ISSUE THREAD

**Issue by zhangruke** [XiaoMi/ozhera#6]
I wonder if there's any plan for link topology in your project.

**Comment by shanwb** [comment]
We believe that link topology is a very valuable feature. We do have plans to incorporate this feature. In the early stages, we may introduce a service call link topology based on minute (or hour) level, which can list the call topology map of the most recent 1 minute (or 1 hour). As progress is made, we will sync in this issue.
Thank you for your attention.

**Comment by sadadw1** [comment]
We are currently working on the network topology diagram with a focus on helping users troubleshoot issues. For instance, if service A is calling service B, and service B is calling service C, and an issue arises in service C, the impact can be traced back to A. We aim to use the network topology diagram to quickly and intuitively pinpoint the problem in C. This requires us to hide some of the successful connections to make it easier to visualize the paths where errors occur.

**Comment by wodiwudi** [comment]
Currently, we have roughly developed the first version of the topology diagram. In the diagram, you can see the topological relationships at the granularity of services, including the provider and the consumer, as well as their availability and invoke number. In the picture, you can also see yellow or red lines, which indicate lower availability. At this point, you can click on the node with lower availability to delve deeper and investigate the root cause of the issue. By clicking layer by layer, you can eventually pinpoint which service or infrastructure is responsible for the service unavailability.
![topo1](https://github.com/XiaoMi/ozhera/assets/40229449/14b4190c-11c9-4a1d-8924-3fa89d1588a9)

![topo2](https://github.com/XiaoMi/ozhera/assets/40229449/7d548aac-6d4f-465a-9462-7d6e07cf2ea2)
